language: node_js
node_js:
  - "0.10"
deploy:
  provider: heroku
  api_key:
    secure: "jYDKgxcwLOS2NsElI296O3FZqVSP1wDsrxV46QjN2qY6uHkXEUeVcfEQFCpTxyCfCnzJrgPpai/CmYW5hc4bUcKnPt0mqYRNbC7t2lLwQpdbDUdUr2G6kRTn/gRnufgx3AHxXDXUe5vA1Q9WS8sKnQdxXMBBriMH5hcSP/PpI8Y="
  app: hanauta-hubot
  strategy: git
notifications:
  slack:
    secure: "UaQq9GSC/3b7sCWSC09hHvyTViStNOCNx6l9WocbvqmKCGUZO1El5SD6btS72o7gJMiKg2bd9rzVcKawIeSaE6yUZ/sZnU4ioDJ+pfLa2DHzR37QYNR9t5egcbEP3d6dT5mvZ6fVtFozrXidA+TWKWeUJtLehCrxxPlzkGUcq5U="