language: node_js
node_js:
  - "0.10"
deploy:
  provider: heroku
  api_key:
    secure: "jYDKgxcwLOS2NsElI296O3FZqVSP1wDsrxV46QjN2qY6uHkXEUeVcfEQFCpTxyCfCnzJrgPpai/CmYW5hc4bUcKnPt0mqYRNbC7t2lLwQpdbDUdUr2G6kRTn/gRnufgx3AHxXDXUe5vA1Q9WS8sKnQdxXMBBriMH5hcSP/PpI8Y="
  app: hanauta-hubot
  strategy: git